name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: debian-bookworm

    steps:
    - uses: actions/checkout@v4se
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --release --verbose
